# -*- coding: utf-8 -*-
"""eeg_label_flipping_defense.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lc8QUV66WIzN3wIIuTnl9wPYvzkV-IIt

### Importing important libraries
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

"""### Here we load the dataset, preprocess and clean (spliting the data into x & y for features and target at the end):"""

def load_dataset(path, drop_outliers = False):
    df = pd.read_csv(path)
    print(f"Dataset size before cleaning & preprocessing: {df.shape}")
    #Removing unnamed column from dataset
    if "Unnamed: 0" in df.columns:
        print("Removing Unnamed Column...")
        df.drop("Unnamed: 0", axis = 1, inplace = True)
    #Checking for missing values
    missing = df.isnull().sum() #per column
    total_missing = missing.sum() #all
    print(f"Total missing values: {total_missing}")
    #Dropping rows with missing values
    if total_missing > 0:
        print("Dropping rows with missing values...")
        b = df.shape[0] #before dropping
        df.dropna(inplace = True)
        a = df.shape[0] #after dropping
        print(f"Dropped {b - a} rows due to missing values.")
    #Dropping duplicated rows
    duplicates = df.duplicated().sum()
    if duplicates > 0:
        print(f"Dropping {duplicates} duplicate rows...")
        df.drop_duplicates(inplace = True)
        print("Dropped duplicates.")
    #Checking and removing outliers
    '''if drop_outliers:
        print("Dropping rows with outliers...")
        numeric_cols = df.select_dtypes(include = np.number).columns
        b = df.shape[0] #rows before dropping outliers
        for col in numeric_cols:
          q1 = df[col].quantile(0.25)
          q3 = df[col].quantile(0.75)
          iqr = q3 - q1
          lower_bound = q1 - 8 * iqr
          upper_bound = q3 + 8 * iqr
          df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
        a = df.shape[0] #rows after dropping outliers
        print(f"Dropped {b - a} rows due to outliers.")'''
    #Features (all columns except the target which is 'Label')
    x = df.drop("Label", axis = 1).values
    #Labels (Targey)
    y = df["Label"].values
    print(f"Dataset size after cleaning & preprocessing: {df.shape}\n")
    return x, y

"""### We scale features so they have mean 0 and standard deviation of 1 (important for models that are sensitive of feature sclaes) and we use the same parameter of the scaler to scale the testing set [must never fit scaler on test set]:
source: https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
"""

def prepare_data(x_train, x_test):
    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)
    return x_train_scaled, x_test_scaled, scaler

"""### Here we train the Random Forest model: (with 200 decision trees to have a more stabel and accurate results & used random_state = 42 to get same results with teammates)

source: https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html
"""

def train_random_forest(x_train, y_train):
    model = RandomForestClassifier(n_estimators = 200, random_state = 42) #we can modify the number of trees to see the effect on results
    model.fit(x_train, y_train) #Train model on training data
    return model

"""### Here we train the SVM model: (kernel by default will be rbf which is a nonlinear kernel, make the model output class probability by saying 'True' and not just class labels (so that we can compute ROC-AUC), and again used random_state = 42 so we could get same results)

source: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
"""

def train_svm(x_train, y_train):
    #model = SVC(kernel = 'linear', probability = True, random_state = 42)
    model = SVC(kernel = 'linear', C = 10, class_weight = 'balanced', probability = True, random_state = 42) #using 'rbf' doesn't work anymore
    model.fit(x_train, y_train) #Train model on training data
    return model

"""### Below we created a method to evaluate the models to keep things organized and quick and reusable for models I, II, and III.
source: https://scikit-learn.org/stable/api/sklearn.metrics.html
"""

def evaluate_model(model, x_test, y_test, title = 'Model Evaluation', return_metrics=False):
    y_pred = model.predict(x_test) #Predicts class labels for dataset x_test (can be used for x_train too, depends on which we pass to the method, here is just a name)
    #if the model supports predict_proba then use it for ROC [Our models support it :)]
    #y_proba = model.predict_proba(x_test) if hasattr(model, "predict_proba") else None
    if hasattr(model, "predict_proba"): #We are checking here to ensure the code doesn't crash if it is not applicable
        y_proba = model.predict_proba(x_test)
    else:
        y_proba = None

    #Calculating the required metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average = "weighted", zero_division = 0) #used weighted average because it weights eacl class score by its real proportion (basically handles class imbalance)
    rec = recall_score(y_test, y_pred, average = "weighted", zero_division = 0) #zero-division = 0 is to set undefined metric to 0 (got error without it)
    f1 = f1_score(y_test, y_pred, average = "weighted", zero_division = 0)

    if y_proba is not None:
        try:
            roc = roc_auc_score(y_test, y_proba, multi_class = 'ovr', average = 'weighted') #used 'ovr' because we have multi-class [one-vs-rest]
        except:
            roc = None
    else:
        roc = None

    #Printing all metrcs calculated
    print("~" * 66) #a divider
    print(title)
    print("~" * 66) #a divider
    print(f"Accuracy:  {acc:.4f}") #Overall fraction of correctly predicted samples
    print(f"Precision: {prec:.4f}") #How many predicted positives are actually positive (best close to 1, worse close to 0)
    print(f"Recall:    {rec:.4f}") #How many actual positives were correctly predicted (best close to 1, worse close to 0)
    print(f"F1 Score:  {f1:.4f}") #Harmonic mean of precision and recall (best close to 1, worse close to 0)
    #print(f"ROC-AUC:   {roc:.4f}" if roc is not None else "ROC-AUC:   Not available for this model")
    #ROC-AUC measures the model's ability to discriminate between classes
    if roc is not None:
        print(f"ROC-AUC:   {roc:.4f}")
    else:
        print("ROC-AUC:   Not available for this model")

    #Computing confusion matrix and plotting it
    classes = [1, 2, 3, 4]
    cm = confusion_matrix(y_test, y_pred, labels = classes) #shows correct vs incorrect prediction for each class [1,2,3,4]

    plt.figure(figsize = (6,5))
    sns.heatmap(cm, annot = True, fmt = "d", cmap = "Blues", xticklabels = classes, yticklabels = classes) #Visual heatmap for better interpretation and displays number od predictions in each box
    plt.title(title + " - Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

    if return_metrics:
      return acc, prec, rec, f1, roc

    #return acc, prec, rec, f1, roc

"""### Now will work on Model I:"""

#Loading training data
x_train, y_train = load_dataset("TRAINING_NORMAL.csv", True)
#Loading testing data
x_test, y_test = load_dataset("TESTING_NORMAL.csv", True)

#Preparing the data
x_train_scaled, x_test_scaled,scaler = prepare_data(x_train, x_test)

#Random Forest training
rf_model = train_random_forest(x_train_scaled, y_train)

#SVM training
svm_model = train_svm(x_train_scaled, y_train)

#Evaluating Random Forest with training set
evaluate_model(rf_model, x_train_scaled, y_train, "Random Forest - Training Set", return_metrics=False)
#Evaluating Random Forest with testing set
evaluate_model(rf_model, x_test_scaled, y_test, "Random Forest - Testing Set", return_metrics=False)

print("\n") #Divider between the 2 models

#Evaluating SVM with training set
evaluate_model(svm_model, x_train_scaled, y_train, "SVM - Training Set", return_metrics=False)
#Evaluating SVM with testing set
evaluate_model(svm_model, x_test_scaled, y_test, "SVM - Testing Set", return_metrics=False)

"""### Trying to do the MLP Model: (Changing hidden layers number and size affects the metrics)"""

def train_mlp(x_train, y_train):
    model = MLPClassifier(hidden_layer_sizes = (64, 32, 16), activation = 'relu', solver = 'adam', max_iter = 500, random_state = 42) #2 hidden layers with 64 & 32 neurons
    model.fit(x_train, y_train) #Train model on training data
    return model

#Training the MLP model
mlp_model = train_mlp(x_train_scaled, y_train)
#Evaluating MLP with training set
evaluate_model(mlp_model, x_train_scaled, y_train, "MLP - Training Set", return_metrics=False)
#Evaluating MLP with testing set
evaluate_model(mlp_model, x_test_scaled, y_test, "MLP - Testing Set", return_metrics=False)

"""## Below is just to see the data and understand it a bit..."""

#Load CSV
df_train = pd.read_csv("TRAINING_NORMAL.csv")
df_test = pd.read_csv("TESTING_NORMAL.csv")

df_train = df_train.drop("Unnamed: 0", axis = 1)
df_test = df_test.drop("Unnamed: 0", axis = 1)

#Print size
print("Training dataset size:", df_train.shape)
print("Testing dataset size: ", df_test.shape)

df_train.columns

print("Training class distribution:\n", df_train['Label'].value_counts())
print("Testing class distribution:\n", df_test['Label'].value_counts())

unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))

unique, counts = np.unique(svm_model.predict(x_train_scaled), return_counts=True)
print(dict(zip(unique, counts)))

"""# Data Poisoning Attack (Model II) - Label Flipping

"""

def poison_labels(y, poison_rate=0.15, random_state=42):

    rng = np.random.RandomState(random_state) #for reproducible randomness

    y = np.array(y)
    y_poisoned = y.copy()

    n_samples = len(y)
    n_poison = int(np.floor(poison_rate * n_samples)) #nr of labels to flip

    #randomly choose which samples to poison
    all_indices = np.arange(n_samples)
    poison_idx = rng.choice(all_indices, size=n_poison, replace=False)

    classes = np.unique(y) #all possible emotion labels

    #flipping labels
    for idx in poison_idx:
        current_label = y[idx]
        #pick a diff. label
        possible_labels = [c for c in classes if c != current_label]
        new_label = rng.choice(possible_labels)
        y_poisoned[idx] = new_label

    return y_poisoned, poison_idx

#create poisoned labels for TRAINING
y_train_poisoned, poisoned_idx = poison_labels(y_train, poison_rate=0.15)

print(f"Number of poisoned samples: {len(poisoned_idx)}")

#train the models on poisoned labels
rf_poison  = train_random_forest(x_train_scaled, y_train_poisoned)
svm_poison = train_svm(x_train_scaled, y_train_poisoned)
mlp_poison = train_mlp(x_train_scaled, y_train_poisoned)

#print("Poisoned (Label-Flipped) Model on TEST set")
evaluate_model(rf_poison,  x_test_scaled, y_test, "RF - Poisoned Test", return_metrics=False)
#evaluate_model(svm_poison, x_test_scaled, y_test, "SVM - Poisoned Test", return_metrics=False)
#evaluate_model(mlp_poison, x_test_scaled, y_test, "MLP - Poisoned Test", return_metrics=False)

"""# Agent-based Defense (Model III)

Agent 1 - Label-Consisteny Agent
"""

class LabelCheckAgent:
    def __init__(self, reference_model, prob_threshold=0.98):
        """
        reference_model : clean baseline model (RF from Model I)
        prob_threshold  : confidence threshold for flagging suspicious labels
        """
        self.model = reference_model
        self.prob_threshold = prob_threshold

    def detect_suspicious(self, X, y):
        """
        Detect samples where the reference model is very confident
        but disagrees with the given label.
        """
        X = np.array(X)
        y = np.array(y)

        probs = self.model.predict_proba(X)
        preds = np.argmax(probs, axis=1)
        max_probs = probs.max(axis=1)

        suspicious_idx = np.where(
            (preds != y) & (max_probs >= self.prob_threshold)
        )[0]

        return suspicious_idx

    def relabel(self, X, y):
        """
        Relabel suspicious samples using the reference model.
        Returns: defended labels + indices that were changed.
        """
        X = np.array(X)
        y_def = np.array(y).copy()

        suspicious_idx = self.detect_suspicious(X, y_def)
        if len(suspicious_idx) > 0:
            corrected = self.model.predict(X[suspicious_idx])
            y_def[suspicious_idx] = corrected

        return y_def, suspicious_idx

#Output of Agent 1 (label consistency / correction)
agent_label = LabelCheckAgent(reference_model=rf_model, prob_threshold=0.98)

y_after_labelcheck, suspicious_idx = agent_label.relabel(x_train_scaled, y_train_poisoned)
X_after_labelcheck = x_train_scaled

print("LabelCheckAgent detected:", len(suspicious_idx), "suspicious samples.")

"""Agent 2 – Centroid Curator Agent"""

#This agent checks distance to class centroid and removes far outliers
def centroid_curator_agent(X, y, contamination_rate=0.03):
    """
    Centroid-based curator:
    - Computes centroid for each class.
    - Measures distance of each point to its class centroid.
    - Removes top contamination_rate fraction with largest distances.
    Returns: X_clean, y_clean, distances
    """
    X = np.array(X)
    y = np.array(y)

    centroids = {}
    unique_labels = np.unique(y)

    for label in unique_labels:
        centroids[label] = X[y == label].mean(axis=0)  # mean vector per class

    distances = np.zeros(len(X))
    for i in range(len(X)):
        centroid = centroids[y[i]]
        distances[i] = np.linalg.norm(X[i] - centroid)

    threshold = np.percentile(distances, 100 - contamination_rate * 100)
    keep_mask = distances <= threshold

    print(f"Centroid-based Curator Agent removed {np.sum(~keep_mask)} suspicious samples.")

    return X[keep_mask], y[keep_mask], distances

X_curated, y_curated, curator_scores = centroid_curator_agent(
    x_train_scaled, y_train_poisoned, contamination_rate=0.03
)

print("Dataset size (after curator):", X_curated.shape)
print("Class distribution (after curator):\n", pd.Series(y_curated).value_counts())

"""Agent 3 – Validator Agent"""

def validator_agent_check(X_clean, y_clean,
                          X_labelcheck, y_labelcheck,
                          X_test, y_test):
    """
    Validator Agent:
    - Train quick LogisticRegression on each cleaned dataset.
    - Compare accuracy on held-out test set.
    - Return True if curator-cleaned data is better or equal.
    """
    #model on curator-cleaned data
    clf_clean = LogisticRegression(max_iter=500)
    clf_clean.fit(X_clean, y_clean)
    acc_clean = clf_clean.score(X_test, y_test)

    #model on label-checked data
    clf_label = LogisticRegression(max_iter=500)
    clf_label.fit(X_labelcheck, y_labelcheck)
    acc_label = clf_label.score(X_test, y_test)

    print("\nValidator Agent Results:")
    print(f"Accuracy (after label-check only): {acc_label:.4f}")
    print(f"Accuracy (after label-check + centroid-curator): {acc_clean:.4f}")

    #return True if curator cleaning is better
    return acc_clean >= acc_label

validation_passed = validator_agent_check(
    X_curated, y_curated,
    X_after_labelcheck, y_after_labelcheck,
    x_test_scaled, y_test
)

if validation_passed:
    print("Validator Agent: Cleaning APPROVED (using label-check + centroid curator output).")
    X_final = X_curated
    y_final = y_curated
else:
    print("Validator Agent: Cleaning REJECTED (using label-check only output).")
    X_final = X_after_labelcheck
    y_final = y_after_labelcheck

print("Final training set shape:", X_final.shape)
print("Final class distribution:\n", pd.Series(y_final).value_counts())

rf_def2  = train_random_forest(X_final, y_final)
svm_def2 = train_svm(X_final, y_final)
mlp_def2 = train_mlp(X_final, y_final)

evaluate_model(rf_def2, x_test_scaled, y_test, "RF - Final Defended Model", return_metrics=False)
#evaluate_model(svm_def2, x_test_scaled, y_test, "SVM - Final Defended Model", return_metrics=False)
#evaluate_model(mlp_def2, x_test_scaled, y_test, "MLP - Final Defended Model", return_metrics=False)

"""# Performance Comparison of Model I (Baseline), Model II (Poisoned) & Model III (Defended)


"""

print("RANDOM FOREST PERFORMANCE COMPARISON: \n")
metrics_baseline = evaluate_model(rf_model, x_test_scaled, y_test, "RF – Model I (Baseline)", return_metrics=True)
metrics_poisoned = evaluate_model(rf_poison, x_test_scaled, y_test, "RF – Model II (Poisoned)", return_metrics=True)
metrics_defended = evaluate_model(rf_def2, x_test_scaled, y_test, "RF – Model III (Defended)", return_metrics=True)

labels = ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"]

baseline_values = metrics_baseline
poisoned_values = metrics_poisoned
defended_values = metrics_defended

x = np.arange(len(labels))
width = 0.25


plt.figure(figsize=(12,5))
plt.grid(True, linestyle='--', alpha=0.5)

plt.bar(x - width, baseline_values, width, label='Model I (Baseline)')
plt.bar(x, poisoned_values, width, label='Model II (Poisoned)')
plt.bar(x + width, defended_values, width, label='Model III (Defended)')

plt.xticks(x, labels)
plt.ylabel("Score")
plt.title("Random Forest – Performance Comparison (Model I vs II vs III)")
plt.legend(loc='lower right')
plt.ylim(0,1)
plt.show()